//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SYS.BLL.DARFON.ChatBot {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChatBotWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ChatBotWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IsRegistedOperationCompleted;
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback ValidateEmailandEmpNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendRegistCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateRegistCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpByEmpNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpByLineIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSimulateEmpByEmpNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGAIASSOredirectURLOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAccOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChatBotWebService() {
            this.Url = global::SYS.BLL.Properties.Settings.Default.SYS_BLL_DARFON_ChatBot_ChatBotWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IsRegistedCompletedEventHandler IsRegistedCompleted;
        
        /// <remarks/>
        public event ValidateEmailandEmpNoCompletedEventHandler ValidateEmailandEmpNoCompleted;
        
        /// <remarks/>
        public event SendRegistCodeCompletedEventHandler SendRegistCodeCompleted;
        
        /// <remarks/>
        public event ValidateRegistCodeCompletedEventHandler ValidateRegistCodeCompleted;
        
        /// <remarks/>
        public event GetEmpByEmpNoCompletedEventHandler GetEmpByEmpNoCompleted;
        
        /// <remarks/>
        public event GetEmpByLineIdCompletedEventHandler GetEmpByLineIdCompleted;
        
        /// <remarks/>
        public event GetSimulateEmpByEmpNoCompletedEventHandler GetSimulateEmpByEmpNoCompleted;
        
        /// <remarks/>
        public event GetEmpByNameCompletedEventHandler GetEmpByNameCompleted;
        
        /// <remarks/>
        public event GetGAIASSOredirectURLCompletedEventHandler GetGAIASSOredirectURLCompleted;
        
        /// <remarks/>
        public event CreateAccCompletedEventHandler CreateAccCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsRegisted", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsRegisted(string lineId) {
            object[] results = this.Invoke("IsRegisted", new object[] {
                        lineId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsRegistedAsync(string lineId) {
            this.IsRegistedAsync(lineId, null);
        }
        
        /// <remarks/>
        public void IsRegistedAsync(string lineId, object userState) {
            if ((this.IsRegistedOperationCompleted == null)) {
                this.IsRegistedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsRegistedOperationCompleted);
            }
            this.InvokeAsync("IsRegisted", new object[] {
                        lineId}, this.IsRegistedOperationCompleted, userState);
        }
        
        private void OnIsRegistedOperationCompleted(object arg) {
            if ((this.IsRegistedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsRegistedCompleted(this, new IsRegistedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateEmailandEmpNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateEmailandEmpNo(string lineId, string email) {
            object[] results = this.Invoke("ValidateEmailandEmpNo", new object[] {
                        lineId,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateEmailandEmpNoAsync(string lineId, string email) {
            this.ValidateEmailandEmpNoAsync(lineId, email, null);
        }
        
        /// <remarks/>
        public void ValidateEmailandEmpNoAsync(string lineId, string email, object userState) {
            if ((this.ValidateEmailandEmpNoOperationCompleted == null)) {
                this.ValidateEmailandEmpNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateEmailandEmpNoOperationCompleted);
            }
            this.InvokeAsync("ValidateEmailandEmpNo", new object[] {
                        lineId,
                        email}, this.ValidateEmailandEmpNoOperationCompleted, userState);
        }
        
        private void OnValidateEmailandEmpNoOperationCompleted(object arg) {
            if ((this.ValidateEmailandEmpNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateEmailandEmpNoCompleted(this, new ValidateEmailandEmpNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendRegistCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendRegistCode(string lineId, string empNo, string empMail) {
            object[] results = this.Invoke("SendRegistCode", new object[] {
                        lineId,
                        empNo,
                        empMail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendRegistCodeAsync(string lineId, string empNo, string empMail) {
            this.SendRegistCodeAsync(lineId, empNo, empMail, null);
        }
        
        /// <remarks/>
        public void SendRegistCodeAsync(string lineId, string empNo, string empMail, object userState) {
            if ((this.SendRegistCodeOperationCompleted == null)) {
                this.SendRegistCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendRegistCodeOperationCompleted);
            }
            this.InvokeAsync("SendRegistCode", new object[] {
                        lineId,
                        empNo,
                        empMail}, this.SendRegistCodeOperationCompleted, userState);
        }
        
        private void OnSendRegistCodeOperationCompleted(object arg) {
            if ((this.SendRegistCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendRegistCodeCompleted(this, new SendRegistCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateRegistCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateRegistCode(string lineId, string code) {
            object[] results = this.Invoke("ValidateRegistCode", new object[] {
                        lineId,
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateRegistCodeAsync(string lineId, string code) {
            this.ValidateRegistCodeAsync(lineId, code, null);
        }
        
        /// <remarks/>
        public void ValidateRegistCodeAsync(string lineId, string code, object userState) {
            if ((this.ValidateRegistCodeOperationCompleted == null)) {
                this.ValidateRegistCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateRegistCodeOperationCompleted);
            }
            this.InvokeAsync("ValidateRegistCode", new object[] {
                        lineId,
                        code}, this.ValidateRegistCodeOperationCompleted, userState);
        }
        
        private void OnValidateRegistCodeOperationCompleted(object arg) {
            if ((this.ValidateRegistCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateRegistCodeCompleted(this, new ValidateRegistCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpByEmpNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpEntity GetEmpByEmpNo(string input) {
            object[] results = this.Invoke("GetEmpByEmpNo", new object[] {
                        input});
            return ((EmpEntity)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpByEmpNoAsync(string input) {
            this.GetEmpByEmpNoAsync(input, null);
        }
        
        /// <remarks/>
        public void GetEmpByEmpNoAsync(string input, object userState) {
            if ((this.GetEmpByEmpNoOperationCompleted == null)) {
                this.GetEmpByEmpNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpByEmpNoOperationCompleted);
            }
            this.InvokeAsync("GetEmpByEmpNo", new object[] {
                        input}, this.GetEmpByEmpNoOperationCompleted, userState);
        }
        
        private void OnGetEmpByEmpNoOperationCompleted(object arg) {
            if ((this.GetEmpByEmpNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpByEmpNoCompleted(this, new GetEmpByEmpNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpByLineId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountRegist GetEmpByLineId(string input) {
            object[] results = this.Invoke("GetEmpByLineId", new object[] {
                        input});
            return ((AccountRegist)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpByLineIdAsync(string input) {
            this.GetEmpByLineIdAsync(input, null);
        }
        
        /// <remarks/>
        public void GetEmpByLineIdAsync(string input, object userState) {
            if ((this.GetEmpByLineIdOperationCompleted == null)) {
                this.GetEmpByLineIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpByLineIdOperationCompleted);
            }
            this.InvokeAsync("GetEmpByLineId", new object[] {
                        input}, this.GetEmpByLineIdOperationCompleted, userState);
        }
        
        private void OnGetEmpByLineIdOperationCompleted(object arg) {
            if ((this.GetEmpByLineIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpByLineIdCompleted(this, new GetEmpByLineIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSimulateEmpByEmpNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountRegist GetSimulateEmpByEmpNo(string input) {
            object[] results = this.Invoke("GetSimulateEmpByEmpNo", new object[] {
                        input});
            return ((AccountRegist)(results[0]));
        }
        
        /// <remarks/>
        public void GetSimulateEmpByEmpNoAsync(string input) {
            this.GetSimulateEmpByEmpNoAsync(input, null);
        }
        
        /// <remarks/>
        public void GetSimulateEmpByEmpNoAsync(string input, object userState) {
            if ((this.GetSimulateEmpByEmpNoOperationCompleted == null)) {
                this.GetSimulateEmpByEmpNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSimulateEmpByEmpNoOperationCompleted);
            }
            this.InvokeAsync("GetSimulateEmpByEmpNo", new object[] {
                        input}, this.GetSimulateEmpByEmpNoOperationCompleted, userState);
        }
        
        private void OnGetSimulateEmpByEmpNoOperationCompleted(object arg) {
            if ((this.GetSimulateEmpByEmpNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSimulateEmpByEmpNoCompleted(this, new GetSimulateEmpByEmpNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpEntity[] GetEmpByName(string lan, string empName) {
            object[] results = this.Invoke("GetEmpByName", new object[] {
                        lan,
                        empName});
            return ((EmpEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpByNameAsync(string lan, string empName) {
            this.GetEmpByNameAsync(lan, empName, null);
        }
        
        /// <remarks/>
        public void GetEmpByNameAsync(string lan, string empName, object userState) {
            if ((this.GetEmpByNameOperationCompleted == null)) {
                this.GetEmpByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpByNameOperationCompleted);
            }
            this.InvokeAsync("GetEmpByName", new object[] {
                        lan,
                        empName}, this.GetEmpByNameOperationCompleted, userState);
        }
        
        private void OnGetEmpByNameOperationCompleted(object arg) {
            if ((this.GetEmpByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpByNameCompleted(this, new GetEmpByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGAIASSOredirectURL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetGAIASSOredirectURL(string apiKey, string sourceSystem, string targetSystem, string userLineId, string targetPage) {
            object[] results = this.Invoke("GetGAIASSOredirectURL", new object[] {
                        apiKey,
                        sourceSystem,
                        targetSystem,
                        userLineId,
                        targetPage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetGAIASSOredirectURLAsync(string apiKey, string sourceSystem, string targetSystem, string userLineId, string targetPage) {
            this.GetGAIASSOredirectURLAsync(apiKey, sourceSystem, targetSystem, userLineId, targetPage, null);
        }
        
        /// <remarks/>
        public void GetGAIASSOredirectURLAsync(string apiKey, string sourceSystem, string targetSystem, string userLineId, string targetPage, object userState) {
            if ((this.GetGAIASSOredirectURLOperationCompleted == null)) {
                this.GetGAIASSOredirectURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGAIASSOredirectURLOperationCompleted);
            }
            this.InvokeAsync("GetGAIASSOredirectURL", new object[] {
                        apiKey,
                        sourceSystem,
                        targetSystem,
                        userLineId,
                        targetPage}, this.GetGAIASSOredirectURLOperationCompleted, userState);
        }
        
        private void OnGetGAIASSOredirectURLOperationCompleted(object arg) {
            if ((this.GetGAIASSOredirectURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGAIASSOredirectURLCompleted(this, new GetGAIASSOredirectURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateAcc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateAcc(AccountRegist input) {
            this.Invoke("CreateAcc", new object[] {
                        input});
        }
        
        /// <remarks/>
        public void CreateAccAsync(AccountRegist input) {
            this.CreateAccAsync(input, null);
        }
        
        /// <remarks/>
        public void CreateAccAsync(AccountRegist input, object userState) {
            if ((this.CreateAccOperationCompleted == null)) {
                this.CreateAccOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAccOperationCompleted);
            }
            this.InvokeAsync("CreateAcc", new object[] {
                        input}, this.CreateAccOperationCompleted, userState);
        }
        
        private void OnCreateAccOperationCompleted(object arg) {
            if ((this.CreateAccCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAccCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountRegist {
        
        private bool activeField;
        
        private System.DateTime cdtField;
        
        private string emp_IdField;
        
        private string emp_mailField;
        
        private string emp_noField;
        
        private string emp_phoneField;
        
        private System.Guid idField;
        
        private string line_IdField;
        
        private string settingField;
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Cdt {
            get {
                return this.cdtField;
            }
            set {
                this.cdtField = value;
            }
        }
        
        /// <remarks/>
        public string Emp_Id {
            get {
                return this.emp_IdField;
            }
            set {
                this.emp_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Emp_mail {
            get {
                return this.emp_mailField;
            }
            set {
                this.emp_mailField = value;
            }
        }
        
        /// <remarks/>
        public string Emp_no {
            get {
                return this.emp_noField;
            }
            set {
                this.emp_noField = value;
            }
        }
        
        /// <remarks/>
        public string Emp_phone {
            get {
                return this.emp_phoneField;
            }
            set {
                this.emp_phoneField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Line_Id {
            get {
                return this.line_IdField;
            }
            set {
                this.line_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpEntity {
        
        private string gAIAIdField;
        
        private string empIdField;
        
        private string empNoField;
        
        private string nameField;
        
        private string enNameField;
        
        private string emailField;
        
        private string siteField;
        
        private string extNoField;
        
        private string isDLField;
        
        private int isActiveField;
        
        private string remarkField;
        
        /// <remarks/>
        public string GAIAId {
            get {
                return this.gAIAIdField;
            }
            set {
                this.gAIAIdField = value;
            }
        }
        
        /// <remarks/>
        public string EmpId {
            get {
                return this.empIdField;
            }
            set {
                this.empIdField = value;
            }
        }
        
        /// <remarks/>
        public string EmpNo {
            get {
                return this.empNoField;
            }
            set {
                this.empNoField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string EnName {
            get {
                return this.enNameField;
            }
            set {
                this.enNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        public string ExtNo {
            get {
                return this.extNoField;
            }
            set {
                this.extNoField = value;
            }
        }
        
        /// <remarks/>
        public string IsDL {
            get {
                return this.isDLField;
            }
            set {
                this.isDLField = value;
            }
        }
        
        /// <remarks/>
        public int IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IsRegistedCompletedEventHandler(object sender, IsRegistedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsRegistedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsRegistedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ValidateEmailandEmpNoCompletedEventHandler(object sender, ValidateEmailandEmpNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateEmailandEmpNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateEmailandEmpNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SendRegistCodeCompletedEventHandler(object sender, SendRegistCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendRegistCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendRegistCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ValidateRegistCodeCompletedEventHandler(object sender, ValidateRegistCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateRegistCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateRegistCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetEmpByEmpNoCompletedEventHandler(object sender, GetEmpByEmpNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpByEmpNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpByEmpNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmpEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmpEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetEmpByLineIdCompletedEventHandler(object sender, GetEmpByLineIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpByLineIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpByLineIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountRegist Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountRegist)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetSimulateEmpByEmpNoCompletedEventHandler(object sender, GetSimulateEmpByEmpNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSimulateEmpByEmpNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSimulateEmpByEmpNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountRegist Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountRegist)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetEmpByNameCompletedEventHandler(object sender, GetEmpByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmpEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmpEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetGAIASSOredirectURLCompletedEventHandler(object sender, GetGAIASSOredirectURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGAIASSOredirectURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGAIASSOredirectURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CreateAccCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591