//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYS.BLL.DARFON.GAIA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DARFON.GAIA.GetEmpSoap")]
    public interface GetEmpSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpByEmpID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SYS.BLL.DARFON.GAIA.EmpALL GetEmpByEmpID(string EmpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpByEmpID", ReplyAction="*")]
        System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALL> GetEmpByEmpIDAsync(string EmpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpByEmpNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SYS.BLL.DARFON.GAIA.EmpALL GetEmpByEmpNo(string EmpNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpByEmpNo", ReplyAction="*")]
        System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALL> GetEmpByEmpNoAsync(string EmpNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpByEmpEnName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SYS.BLL.DARFON.GAIA.EmpALL GetEmpByEmpEnName(string EmpEnName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpByEmpEnName", ReplyAction="*")]
        System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALL> GetEmpByEmpEnNameAsync(string EmpEnName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpByDeptCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SYS.BLL.DARFON.GAIA.EmpALL[] GetEmpByDeptCode(string DeptCode, string Active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpByDeptCode", ReplyAction="*")]
        System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALL[]> GetEmpByDeptCodeAsync(string DeptCode, string Active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpBySiteCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SYS.BLL.DARFON.GAIA.EmpALL[] GetEmpBySiteCode(string SiteCode, string Active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpBySiteCode", ReplyAction="*")]
        System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALL[]> GetEmpBySiteCodeAsync(string SiteCode, string Active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChangeDateByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SYS.BLL.DARFON.GAIA.EmpALLMain[] GetChangeDateByDate(System.DateTime Stdate, System.DateTime EdDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChangeDateByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALLMain[]> GetChangeDateByDateAsync(System.DateTime Stdate, System.DateTime EdDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetALLEmp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SYS.BLL.DARFON.GAIA.EmpALLMain[] GetALLEmp(string site, string Active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetALLEmp", ReplyAction="*")]
        System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALLMain[]> GetALLEmpAsync(string site, string Active);
        
        // CODEGEN: Generating message contract since message EmpAccountVerificationRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpAccountVerification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SYS.BLL.DARFON.GAIA.EmpAccountVerificationResponse EmpAccountVerification(SYS.BLL.DARFON.GAIA.EmpAccountVerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmpAccountVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpAccountVerificationResponse> EmpAccountVerificationAsync(SYS.BLL.DARFON.GAIA.EmpAccountVerificationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpALL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string empIDField;
        
        private string empNameField;
        
        private string empEnNameField;
        
        private string siteCodeField;
        
        private string activeField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private System.Nullable<System.DateTime> editDateField;
        
        private System.Nullable<System.Guid> gaiaIDField;
        
        private string flowerIDField;
        
        private string empTypeField;
        
        private string eMailField;
        
        private System.Nullable<System.DateTime> hireDayField;
        
        private System.Nullable<System.DateTime> leaveDayField;
        
        private string sexField;
        
        private System.Nullable<System.DateTime> birthdayField;
        
        private EmpInfo_Dto[] empInfosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmpID {
            get {
                return this.empIDField;
            }
            set {
                this.empIDField = value;
                this.RaisePropertyChanged("EmpID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EmpName {
            get {
                return this.empNameField;
            }
            set {
                this.empNameField = value;
                this.RaisePropertyChanged("EmpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EmpEnName {
            get {
                return this.empEnNameField;
            }
            set {
                this.empEnNameField = value;
                this.RaisePropertyChanged("EmpEnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SiteCode {
            get {
                return this.siteCodeField;
            }
            set {
                this.siteCodeField = value;
                this.RaisePropertyChanged("SiteCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> EditDate {
            get {
                return this.editDateField;
            }
            set {
                this.editDateField = value;
                this.RaisePropertyChanged("EditDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.Guid> GaiaID {
            get {
                return this.gaiaIDField;
            }
            set {
                this.gaiaIDField = value;
                this.RaisePropertyChanged("GaiaID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FlowerID {
            get {
                return this.flowerIDField;
            }
            set {
                this.flowerIDField = value;
                this.RaisePropertyChanged("FlowerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EmpType {
            get {
                return this.empTypeField;
            }
            set {
                this.empTypeField = value;
                this.RaisePropertyChanged("EmpType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
                this.RaisePropertyChanged("EMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> HireDay {
            get {
                return this.hireDayField;
            }
            set {
                this.hireDayField = value;
                this.RaisePropertyChanged("HireDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> LeaveDay {
            get {
                return this.leaveDayField;
            }
            set {
                this.leaveDayField = value;
                this.RaisePropertyChanged("LeaveDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        public EmpInfo_Dto[] EmpInfos {
            get {
                return this.empInfosField;
            }
            set {
                this.empInfosField = value;
                this.RaisePropertyChanged("EmpInfos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpInfo_Dto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string empIDField;
        
        private string empNoField;
        
        private string empNameField;
        
        private string empEnNameField;
        
        private string siteIDField;
        
        private string deptCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmpID {
            get {
                return this.empIDField;
            }
            set {
                this.empIDField = value;
                this.RaisePropertyChanged("EmpID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EmpNo {
            get {
                return this.empNoField;
            }
            set {
                this.empNoField = value;
                this.RaisePropertyChanged("EmpNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EmpName {
            get {
                return this.empNameField;
            }
            set {
                this.empNameField = value;
                this.RaisePropertyChanged("EmpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EmpEnName {
            get {
                return this.empEnNameField;
            }
            set {
                this.empEnNameField = value;
                this.RaisePropertyChanged("EmpEnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
                this.RaisePropertyChanged("SiteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DeptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
                this.RaisePropertyChanged("DeptCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class mySoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accField;
        
        private string pwdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Acc {
            get {
                return this.accField;
            }
            set {
                this.accField = value;
                this.RaisePropertyChanged("Acc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
                this.RaisePropertyChanged("Pwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string empIDField;
        
        private string empNoField;
        
        private string empEnNameField;
        
        private string pwdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmpID {
            get {
                return this.empIDField;
            }
            set {
                this.empIDField = value;
                this.RaisePropertyChanged("EmpID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EmpNo {
            get {
                return this.empNoField;
            }
            set {
                this.empNoField = value;
                this.RaisePropertyChanged("EmpNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EmpEnName {
            get {
                return this.empEnNameField;
            }
            set {
                this.empEnNameField = value;
                this.RaisePropertyChanged("EmpEnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
                this.RaisePropertyChanged("Pwd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpALLMain : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string empIDField;
        
        private string empNameField;
        
        private string empEnNameField;
        
        private string siteCodeField;
        
        private string empNoField;
        
        private string activeField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private System.Nullable<System.DateTime> editDateField;
        
        private System.Nullable<System.Guid> gaiaIDField;
        
        private string flowerIDField;
        
        private string empTypeField;
        
        private string eMailField;
        
        private System.Nullable<System.DateTime> hireDayField;
        
        private System.Nullable<System.DateTime> leaveDayField;
        
        private string sexField;
        
        private System.Nullable<System.DateTime> birthdayField;
        
        private string deptCodeField;
        
        private string jobClassField;
        
        private string rankField;
        
        private string extField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmpID {
            get {
                return this.empIDField;
            }
            set {
                this.empIDField = value;
                this.RaisePropertyChanged("EmpID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EmpName {
            get {
                return this.empNameField;
            }
            set {
                this.empNameField = value;
                this.RaisePropertyChanged("EmpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EmpEnName {
            get {
                return this.empEnNameField;
            }
            set {
                this.empEnNameField = value;
                this.RaisePropertyChanged("EmpEnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SiteCode {
            get {
                return this.siteCodeField;
            }
            set {
                this.siteCodeField = value;
                this.RaisePropertyChanged("SiteCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EmpNo {
            get {
                return this.empNoField;
            }
            set {
                this.empNoField = value;
                this.RaisePropertyChanged("EmpNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> EditDate {
            get {
                return this.editDateField;
            }
            set {
                this.editDateField = value;
                this.RaisePropertyChanged("EditDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.Guid> GaiaID {
            get {
                return this.gaiaIDField;
            }
            set {
                this.gaiaIDField = value;
                this.RaisePropertyChanged("GaiaID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FlowerID {
            get {
                return this.flowerIDField;
            }
            set {
                this.flowerIDField = value;
                this.RaisePropertyChanged("FlowerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string EmpType {
            get {
                return this.empTypeField;
            }
            set {
                this.empTypeField = value;
                this.RaisePropertyChanged("EmpType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
                this.RaisePropertyChanged("EMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> HireDay {
            get {
                return this.hireDayField;
            }
            set {
                this.hireDayField = value;
                this.RaisePropertyChanged("HireDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> LeaveDay {
            get {
                return this.leaveDayField;
            }
            set {
                this.leaveDayField = value;
                this.RaisePropertyChanged("LeaveDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DeptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
                this.RaisePropertyChanged("DeptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string JobClass {
            get {
                return this.jobClassField;
            }
            set {
                this.jobClassField = value;
                this.RaisePropertyChanged("JobClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("Rank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ext {
            get {
                return this.extField;
            }
            set {
                this.extField = value;
                this.RaisePropertyChanged("ext");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmpAccountVerification", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmpAccountVerificationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SYS.BLL.DARFON.GAIA.mySoapHeader mySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SYS.BLL.DARFON.GAIA.AccountDto Empacc;
        
        public EmpAccountVerificationRequest() {
        }
        
        public EmpAccountVerificationRequest(SYS.BLL.DARFON.GAIA.mySoapHeader mySoapHeader, SYS.BLL.DARFON.GAIA.AccountDto Empacc) {
            this.mySoapHeader = mySoapHeader;
            this.Empacc = Empacc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmpAccountVerificationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmpAccountVerificationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EmpAccountVerificationResult;
        
        public EmpAccountVerificationResponse() {
        }
        
        public EmpAccountVerificationResponse(string EmpAccountVerificationResult) {
            this.EmpAccountVerificationResult = EmpAccountVerificationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetEmpSoapChannel : SYS.BLL.DARFON.GAIA.GetEmpSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEmpSoapClient : System.ServiceModel.ClientBase<SYS.BLL.DARFON.GAIA.GetEmpSoap>, SYS.BLL.DARFON.GAIA.GetEmpSoap {
        
        public GetEmpSoapClient() {
        }
        
        public GetEmpSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetEmpSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetEmpSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetEmpSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public SYS.BLL.DARFON.GAIA.EmpALL GetEmpByEmpID(string EmpID) {
            return base.Channel.GetEmpByEmpID(EmpID);
        }
        
        public System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALL> GetEmpByEmpIDAsync(string EmpID) {
            return base.Channel.GetEmpByEmpIDAsync(EmpID);
        }
        
        public SYS.BLL.DARFON.GAIA.EmpALL GetEmpByEmpNo(string EmpNo) {
            return base.Channel.GetEmpByEmpNo(EmpNo);
        }
        
        public System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALL> GetEmpByEmpNoAsync(string EmpNo) {
            return base.Channel.GetEmpByEmpNoAsync(EmpNo);
        }
        
        public SYS.BLL.DARFON.GAIA.EmpALL GetEmpByEmpEnName(string EmpEnName) {
            return base.Channel.GetEmpByEmpEnName(EmpEnName);
        }
        
        public System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALL> GetEmpByEmpEnNameAsync(string EmpEnName) {
            return base.Channel.GetEmpByEmpEnNameAsync(EmpEnName);
        }
        
        public SYS.BLL.DARFON.GAIA.EmpALL[] GetEmpByDeptCode(string DeptCode, string Active) {
            return base.Channel.GetEmpByDeptCode(DeptCode, Active);
        }
        
        public System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALL[]> GetEmpByDeptCodeAsync(string DeptCode, string Active) {
            return base.Channel.GetEmpByDeptCodeAsync(DeptCode, Active);
        }
        
        public SYS.BLL.DARFON.GAIA.EmpALL[] GetEmpBySiteCode(string SiteCode, string Active) {
            return base.Channel.GetEmpBySiteCode(SiteCode, Active);
        }
        
        public System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALL[]> GetEmpBySiteCodeAsync(string SiteCode, string Active) {
            return base.Channel.GetEmpBySiteCodeAsync(SiteCode, Active);
        }
        
        public SYS.BLL.DARFON.GAIA.EmpALLMain[] GetChangeDateByDate(System.DateTime Stdate, System.DateTime EdDate) {
            return base.Channel.GetChangeDateByDate(Stdate, EdDate);
        }
        
        public System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALLMain[]> GetChangeDateByDateAsync(System.DateTime Stdate, System.DateTime EdDate) {
            return base.Channel.GetChangeDateByDateAsync(Stdate, EdDate);
        }
        
        public SYS.BLL.DARFON.GAIA.EmpALLMain[] GetALLEmp(string site, string Active) {
            return base.Channel.GetALLEmp(site, Active);
        }
        
        public System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpALLMain[]> GetALLEmpAsync(string site, string Active) {
            return base.Channel.GetALLEmpAsync(site, Active);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SYS.BLL.DARFON.GAIA.EmpAccountVerificationResponse SYS.BLL.DARFON.GAIA.GetEmpSoap.EmpAccountVerification(SYS.BLL.DARFON.GAIA.EmpAccountVerificationRequest request) {
            return base.Channel.EmpAccountVerification(request);
        }
        
        public string EmpAccountVerification(SYS.BLL.DARFON.GAIA.mySoapHeader mySoapHeader, SYS.BLL.DARFON.GAIA.AccountDto Empacc) {
            SYS.BLL.DARFON.GAIA.EmpAccountVerificationRequest inValue = new SYS.BLL.DARFON.GAIA.EmpAccountVerificationRequest();
            inValue.mySoapHeader = mySoapHeader;
            inValue.Empacc = Empacc;
            SYS.BLL.DARFON.GAIA.EmpAccountVerificationResponse retVal = ((SYS.BLL.DARFON.GAIA.GetEmpSoap)(this)).EmpAccountVerification(inValue);
            return retVal.EmpAccountVerificationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpAccountVerificationResponse> SYS.BLL.DARFON.GAIA.GetEmpSoap.EmpAccountVerificationAsync(SYS.BLL.DARFON.GAIA.EmpAccountVerificationRequest request) {
            return base.Channel.EmpAccountVerificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SYS.BLL.DARFON.GAIA.EmpAccountVerificationResponse> EmpAccountVerificationAsync(SYS.BLL.DARFON.GAIA.mySoapHeader mySoapHeader, SYS.BLL.DARFON.GAIA.AccountDto Empacc) {
            SYS.BLL.DARFON.GAIA.EmpAccountVerificationRequest inValue = new SYS.BLL.DARFON.GAIA.EmpAccountVerificationRequest();
            inValue.mySoapHeader = mySoapHeader;
            inValue.Empacc = Empacc;
            return ((SYS.BLL.DARFON.GAIA.GetEmpSoap)(this)).EmpAccountVerificationAsync(inValue);
        }
    }
}
